### ISSUE TITLE
Alternate Selector

### ISSUE THREAD

**Issue by cyouh95** [glennrosenberg/Dasmoto#3]
Alternatively, you could use the selector `#brushes h2`, for example, and omit creating a new class for each (ie. `.mediumspringgreen`)

https://github.com/glennrosenberg/Dasmoto/blob/master/resources/style.css#L21

**Comment by glennrosenberg** [comment]
I thought about this and decided that I would normally create the class so I could reuse it elsewhere in the site to maintain consistent look & feel.  I suppose for the purpose of the assignment it makes sense to practice using different selectors - updated per the comment
