### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [glennrosenberg/Dasmoto#5]
(Exceeds Expectations)

Well done on this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And great job with the use of classes and IDs, including adding the hyperlinks to jump to each section!

As a further challenge, try expanding this page and play around with adding some of your own elements to it. As you do, continue to explore how to best select and style your elements, including taking advantage of property inheritance to avoid repetition in code (#2, #3). Also, you could look more into the different types of [CSS properties](https://www.w3schools.com/cssref/default.asp) available (#4). Happy coding!

**Comment by glennrosenberg** [comment]
Updated content based on comments from cyouh95 and committed all changes to branch:master.  I will have a look through the CSS properties in the provided link - thanks.
